version: '3.9'

services:
  tester:
    build: .
    env_file: test.env
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER}:/workspace
      - node_modules:/workspace/e2e/node_modules
    stdin_open: true
    init: true
    command: /bin/bash
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 0.8s
      retries: 50

volumes:
  node_modules: