#!/bin/bash
echo "UID=$(id -u $USER)" > .devcontainer/.env
echo "GID=$(id -g $USER)" >> .devcontainer/.env
echo "USERNAME_=$USER" >> .devcontainer/.env
echo "LOCAL_WORKSPACE_FOLDER=$PWD" >> .devcontainer/.env
